"""empty message

Revision ID: 09e553539553
Revises: 7aaa20bebcfc
Create Date: 2020-06-28 18:37:15.620804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e553539553'
down_revision = '7aaa20bebcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('issue_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'issue_file')
    # ### end Alembic commands ###
