"""empty message

Revision ID: 34fb501946ae
Revises: eb10a061c78e
Create Date: 2020-07-10 14:26:05.254295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34fb501946ae'
down_revision = 'eb10a061c78e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_engineers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('support_engineer_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('issues', sa.Column('support_engineer', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'support_engineer')
    op.drop_table('support_engineers')
    # ### end Alembic commands ###
