"""empty message

Revision ID: 7aaa20bebcfc
Revises: b1d8da2b3f42
Create Date: 2020-06-28 18:35:35.053149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aaa20bebcfc'
down_revision = 'b1d8da2b3f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('issue_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'issue_file')
    # ### end Alembic commands ###
