"""empty message

Revision ID: b1d8da2b3f42
Revises: 15b5bada3a11
Create Date: 2020-06-28 18:35:20.420423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d8da2b3f42'
down_revision = '15b5bada3a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('issue_file', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'issue_file')
    # ### end Alembic commands ###
